<?php
/**
 * Template for displaying the import errors.
 *
 * @category    C4B
 * @package     C4B_XmlImport
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software Licence 3.0 (OSL-3.0)
 * @author      Dominik Meglic <meglic@code4business.de>
 * @copyright   code4business Software GmbH
 */

/* @var $this C4B_XmlImport_Block_ImportError */
?>
<h2>Results from importing in <a href="<?php echo Mage::getBaseUrl()?>"><?php echo Mage::getBaseUrl()?></a></h2>
<table>
    <tr><td>Start time:</td><td colspan="2"><?php echo $this->getStartTime() ?></td><tr/>
    <tr><td>Time taken:</td><td><?php echo round($this->getTimeTaken(),3) ?> s</td><td>(<?php echo round(($this->getTimeTaken() / 60) ,2) ?> min)</td><tr/>
    <tr><td>Memory used:</td><td colspan="2"><?php echo $this->getMemoryUsed() ?></td><tr/>
    <tr><td>Number of imported files:</td><td colspan="2"><?php echo $this->getFileCount() ?></td></tr>
    <tr><td>Number of files with errors:</td><td colspan="2"><?php echo $this->getErrorFileCount() ?></td></tr>
</table>
<br />
<?php foreach($this->getErrors() as $fileName => $productErrors):?>
    <h5>File: <span><?php echo $fileName ?></span></h5>
    <table>
        <tr>
            <td style="border: 1px; border-style: solid;">Product position</td>
            <td style="border: 1px; border-style: solid;">Error</td>
        </tr>
        
            <?php foreach($productErrors as $productPosition => $errors):?>
            <?php $rowspanProductPosition = count($errors) ?>
                    <?php foreach($errors as $number => $errorMessage): ?>
                    <tr>
                        <?php if($number === 0):?>
                            <td style="border: 1px; border-style: solid;" rowspan="<?php echo $rowspanProductPosition ?>"><?php echo $productPosition?></td>
                        <?php endif; ?>
                        <td style="border: 1px; border-style: solid;"><?php echo $errorMessage ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
    </table>
<?php endforeach; ?>