<?php
/**
 * Template for displaying the import error results.
 *
 * @category    C4B
 * @package     C4B_XmlImport
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software Licence 3.0 (OSL-3.0)
 * @author      Dominik Meglic <meglic@code4business.de>
 * @copyright   code4business Software GmbH
 */

/* @var $this C4B_XmlImport_Block_MissingAttributes */
?>
<h2>Missing attributes </h2>
<h2><a href="<?php echo Mage::getBaseUrl()?>"><?php echo Mage::getBaseUrl()?></a></h2>
<br />
<p>Import file contains attributes that do not exist in the system</p>
<ul>
<?php foreach($this->getAttributesList() as $missingAttribute):?>
    <li><?php echo $missingAttribute ?></li>
<?php endforeach;?>
</ul>
<hr />
<?php if($this->getAreAttributesCreated()):?>
    <p>These attributes were created. For successful completion of importing please assign the attributes to the needed attribute sets
     and run importing with the same file again.</p>
 <?php endif;?>